name: Build/publish release

on: [push, pull_request]

permissions:
  contents: write

jobs:
  publish:
    name: Binary ${{ matrix.target }} (on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   target: x86_64-unknown-linux-musl
          #   cross: true
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: true
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-musl
          #   cross: true
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          #   cross: true
          # - os: ubuntu-latest
          #   target: armv7-unknown-linux-musleabihf
          #   cross: true
          # - os: ubuntu-latest
          #   target: armv7-unknown-linux-gnueabihf
          #   cross: true
          # - os: ubuntu-latest
          #   target: arm-unknown-linux-musleabihf
          #   cross: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            cross: false
          - os: macos-latest
            target: x86_64-apple-darwin
            cross: false
          # - os: ubuntu-latest
          #   target: x86_64-unknown-freebsd
          #   cross: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # - run: sudo apt install musl-tools
      #   if: startsWith(matrix.os, 'ubuntu')

      - run: sudo apt install libwayland-dev
        if: startsWith(matrix.os, 'ubuntu')

      - name: cargo build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          args: --release --locked ${{ matrix.cargo_flags }}
          target: ${{ matrix.target }}

      - name: Set exe extension for Windows
        run: echo "EXE=.exe" >> $env:GITHUB_ENV
        if: startsWith(matrix.os, 'windows')

      - name: Add icon for Windows
        run: |
          curl -LO https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe
          ./rcedit-x64.exe target/${{ matrix.target }}/release/ReXOR${{ env.EXE }} --set-icon assets/icon.ico
        if: startsWith(matrix.os, 'windows')
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/ReXOR${{ env.EXE }}

      - name: Get version from tag
        id: extract_version
        run: |
          echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Install CHANGELOG parser
        uses: taiki-e/install-action@parse-changelog

      - name: Get CHANGELOG entry
        run: parse-changelog CHANGELOG.md ${{ steps.extract_version.outputs.version }} | tee changelog_entry
        if: startsWith(github.ref_name, 'v') && github.ref_type == 'tag'
        shell: bash

      - name: Read changelog entry from file
        id: changelog_entry
        uses: juliangruber/read-file-action@v1
        with:
          path: ./changelog_entry
        if: startsWith(github.ref_name, 'v') && github.ref_type == 'tag'

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/ReXOR${{ env.EXE }}
          tag: ${{ github.ref_name }}
          asset_name: ReXOR-${{ steps.extract_version.outputs.version }}-${{ matrix.target }}${{ env.EXE }}
          body: ${{ steps.changelog_entry.outputs.content }}
        if: startsWith(github.ref_name, 'v') && github.ref_type == 'tag'
